-- Initiates needed tables within the SQL file.

-- Creates the users table, allows for username and password_hash with an auto increment for id.
CREATE TABLE IF NOT EXISTS users (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL
);

-- Inserts the default user 'admin' with the password 'school' into the users table.
INSERT IGNORE INTO users (username, password_hash)
VALUES ('admin', '$2y$10$iMQJAMvOl51LtxI6.8lx1uxrri8fxUoa0lHqA9t6GLc8.VG2mrxpu');

-- Creates the pupils table.
CREATE TABLE IF NOT EXISTS classes (
  class_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  capacity INT NOT NULL
);

INSERT INTO classes (name, capacity) VALUES
('Reception', 5),
('Year One', 5),
('Year Two', 5),
('Year Three', 5),
('Year Four', 5),
('Year Five', 5),
('Year Six', 5);

CREATE TABLE IF NOT EXISTS teachers (
  teacher_id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  address TEXT NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone_number VARCHAR(20) NOT NULL,
  annual_salary DECIMAL(10, 2) NOT NULL,
  background_check BOOLEAN DEFAULT FALSE NOT NULL,
  class_id INT,
  FOREIGN KEY (class_id) REFERENCES classes(class_id) ON DELETE SET NULL
);

-- DUMMY TEACHER DATA (GENERATED BY AI)

INSERT INTO teachers (full_name, address, email, phone_number, annual_salary, background_check, class_id) VALUES 
-- Class 1 (Reception)
('Sarah Miller', '101 Maple Drive, Manchester', 's.miller@stalphonsus.sch.uk', '07700 900101', 32000.00, 1, 1),

-- Class 2 (Year One)
('David Brown', '22 Oak Avenue, Salford', 'd.brown@stalphonsus.sch.uk', '07700 900102', 34500.00, 1, 2),

-- Class 3 (Year Two)
('Jessica Taylor', '55 Pine Road, Stockport', 'j.taylor@stalphonsus.sch.uk', '07700 900103', 33000.00, 1, 3),

-- Class 4 (Year Three)
('James Wilson', '8 Elm Street, Bolton', 'j.wilson@stalphonsus.sch.uk', '07700 900104', 38000.00, 1, 4),

-- Class 5 (Year Four)
('Emily Evans', '14 Birch Lane, Rochdale', 'e.evans@stalphonsus.sch.uk', '07700 900105', 39500.00, 1, 5),

-- Class 6 (Year Five)
('Thomas Clarke', '90 Cedar Close, Manchester', 't.clarke@stalphonsus.sch.uk', '07700 900106', 41200.00, 1, 6),

-- Class 7 (Year Six)
('Sophie Turner', '33 Willow Way, Manchester', 's.turner@stalphonsus.sch.uk', '07700 900107', 45000.00, 1, 7);

CREATE TABLE IF NOT EXISTS pupils (
  pupil_id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  address TEXT NOT NULL,
  birthday DATE NOT NULL,
  medical_info TEXT,
  class_id INT,
  FOREIGN KEY (class_id) REFERENCES classes(class_id) ON DELETE SET NULL
);

-- DUMMY PUPIL DATA (GENERATED BY AI)

-- 1. RECEPTION (Class ID 1)
INSERT INTO pupils (full_name, address, birthday, medical_info, class_id) VALUES 
('Oliver Smith', '12 High Street, Manchester', '2020-09-15', NULL, 1),
('Amelia Jones', '4 Church Lane, Salford', '2021-02-10', 'Mild Asthma', 1),
('George Taylor', '89 Victoria Road, Trafford', '2020-11-05', NULL, 1),
('Isla Brown', '3 Station Road, Stockport', '2021-05-22', NULL, 1),
('Noah Williams', '22 Park Avenue, Manchester', '2020-12-30', 'Peanut Allergy (Epipen)', 1);

-- 2. YEAR ONE (Class ID 2)
INSERT INTO pupils (full_name, address, birthday, medical_info, class_id) VALUES 
('Arthur Davies', '56 Main Street, Bolton', '2019-10-12', NULL, 2),
('Ava Evans', '101 The Crescent, Bury', '2020-03-01', NULL, 2),
('Leo Wilson', '7 Queensway, Wigan', '2019-09-25', 'Eczema', 2),
('Mia Thomas', '12 Mill Lane, Rochdale', '2020-01-14', NULL, 2),
('Oscar Roberts', '45 King Street, Oldham', '2019-11-08', NULL, 2);

-- 3. YEAR TWO (Class ID 3)
INSERT INTO pupils (full_name, address, birthday, medical_info, class_id) VALUES 
('Harry Johnson', '34 York Road, Manchester', '2018-12-01', 'Dairy Intolerance', 3),
('Grace Robinson', '78 Windsor Drive, Sale', '2019-04-17', NULL, 3),
('Archie Wright', '90 London Road, Manchester', '2018-09-05', NULL, 3),
('Lily Thompson', '5 Baker Street, Altrincham', '2019-06-23', NULL, 3),
('Henry White', '11 Green Lane, Manchester', '2019-01-30', 'Hayfever', 3);

-- 4. YEAR THREE (Class ID 4)
INSERT INTO pupils (full_name, address, birthday, medical_info, class_id) VALUES 
('Jack Hall', '67 Stanley Road, Manchester', '2017-10-05', NULL, 4),
('Freya Green', '23 Orchard Close, Didsbury', '2018-02-14', NULL, 4),
('Freddie Walker', '89 Albert Street, Chorlton', '2017-11-20', 'Coeliac Disease', 4),
('Sophia Edwards', '14 Manor Park, Manchester', '2018-05-09', NULL, 4),
('Charlie Wood', '88 West Street, Salford', '2017-09-15', NULL, 4);

-- 5. YEAR FOUR (Class ID 5)
INSERT INTO pupils (full_name, address, birthday, medical_info, class_id) VALUES 
('Alfie Harris', '33 North Road, Manchester', '2016-12-25', NULL, 5),
('Emily Martin', '21 Chester Road, Stretford', '2017-03-10', 'Asthma', 5),
('Theo Jackson', '66 South Street, Manchester', '2016-09-09', NULL, 5),
('Poppy Clarke', '99 East Avenue, Manchester', '2017-07-04', NULL, 5),
('Jacob Clark', '15 The Avenue, Manchester', '2017-01-19', 'Bee Sting Allergy', 5);

-- 6. YEAR FIVE (Class ID 6)
INSERT INTO pupils (full_name, address, birthday, medical_info, class_id) VALUES 
('Thomas Lewis', '10 Downing Road, Manchester', '2015-11-11', NULL, 6),
('Daisy Lee', '44 River View, Salford Quays', '2016-04-02', NULL, 6),
('James Scott', '12 Hill Top, Manchester', '2015-10-31', 'Type 1 Diabetes', 6),
('Florence Hill', '77 Garden Row, Manchester', '2016-06-15', NULL, 6),
('William Moore', '28 The Green, Hale', '2016-01-01', NULL, 6);

-- 7. YEAR SIX (Class ID 7)
INSERT INTO pupils (full_name, address, birthday, medical_info, class_id) VALUES 
('Joshua King', '55 Castle Street, Manchester', '2014-09-20', NULL, 7),
('Evie Baker', '99 Forest Way, Manchester', '2015-02-28', NULL, 7),
('Ethan Nelson', '31 Meadow Lane, Manchester', '2014-12-12', 'Mild Eczema', 7),
('Charlotte Carter', '22 Brookside, Manchester', '2015-05-05', NULL, 7),
('Daniel Mitchell', '88 Lake View, Manchester', '2014-10-08', NULL, 7);

CREATE TABLE IF NOT EXISTS guardians (
  guardian_id INT AUTO_INCREMENT PRIMARY KEY,
  full_name VARCHAR(100) NOT NULL,
  address TEXT NOT NULL,
  email VARCHAR(100) NOT NULL,
  phone_number VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS guardian_pupil (
  pupil_id INT,
  guardian_id INT,
  PRIMARY KEY (pupil_id, guardian_id),
  FOREIGN KEY (pupil_id) REFERENCES pupils(pupil_id) ON DELETE CASCADE,
  FOREIGN KEY (guardian_id) REFERENCES guardians(guardian_id) ON DELETE CASCADE
);
